### ISSUE TITLE
Empty string as keyboard name

### ISSUE THREAD

**Issue by emcek** [emcek/dcspy#221]
**Describe the bug**
Empty string as keyboard name.

Setting:
`keyboard: ''`
sas weird side effects

```
DEBUG   | QThreadPool with 8 thread(s)
Critical error: 'DcsPyQtGui' object has no attribute 'rb_'
Traceback (most recent call last):
  File "D:\Projects\dcspy_dev\dcspy\run.py", line 25, in run
    window = DcsPyQtGui()
             ^^^^^^^^^^^^
  File "D:\Projects\dcspy_dev\dcspy\qt_gui.py", line 85, in __init__
    self.apply_configuration(cfg=self.config)
  File "D:\Projects\dcspy_dev\dcspy\qt_gui.py", line 1057, in apply_configuration
    getattr(self, f'rb_{cfg["keyboard"].lower().replace(" ", "")}').toggle()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DcsPyQtGui' object has no attribute 'rb_'
```

**Comment by emcek** [comment]
Several different problem with config parameters were identify:
* parsing wrong bool values
* parsing wrong integer values
